modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/gigaherz/PackingTape/issues"
license="BSD (3 clause)"

[[mods]]
modId="packingtape"
version="${file.jarVersion}"
displayName="Packing Tape"
description='''
Adds a simple means to carry thigns with you
'''
displayURL="https://github.com/gigaherz/PackingTape"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.packingtape]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.0-alpha,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.packingtape]]
    modId="minecraft"
    type="required"
    versionRange="[1.21-alpha,1.22)"
    ordering="NONE"
    side="BOTH"